"""Actor process: generates sequences using vLLM AsyncLLMEngine with
true mid-sequence in-flight weight updates.

Implements Algorithm 2 (Actor Process) from the PipelineRL paper.

The Actor uses vLLM's AsyncLLMEngine with continuous batching. Multiple
generation requests run concurrently inside vLLM. When the Trainer
publishes new weights, the Actor calls reload_weights() — all sequences
currently being generated will use the NEW weights for their remaining
tokens. This creates true "mixed-policy" sequences:

    tokens 1..k  → generated by policy v_old
    tokens k+1..n → generated by policy v_new

This is the core innovation of PipelineRL — generation never stops,
and the model is always using the freshest available weights.
"""

import asyncio
import logging
import os
import random
import time
import uuid
from dataclasses import dataclass
from typing import Optional

from .config import PipelineRLConfig
from .reward import compute_reward
from .weight_sync import WeightSynchronizer

logger = logging.getLogger("pipelinerl")


@dataclass
class SequenceResult:
    """A completed sequence with all metadata needed for training.

    Tracks both start and end weight versions to capture the "mixed-policy"
    nature of PipelineRL sequences. Due to in-flight updates, a single
    sequence may span multiple policy versions:

        tokens 1..k   → generated by policy at start_weight_version
        tokens k+1..n → generated by policy at end_weight_version

    This per-token lag structure is illustrated in Figure 3a of the paper.
    """

    prompt: str
    question: str
    response: str
    ground_truth: str
    reward: float
    log_probs: list[float]  # per-token log probs under behavior policy
    start_weight_version: int  # weight version when generation STARTED
    end_weight_version: int  # weight version when generation FINISHED
    num_tokens: int


def actor_main(
    config: PipelineRLConfig,
    train_queue,  # unused in subprocess mode
    weight_sync: WeightSynchronizer,
    prompts: list[dict],
    done_event,  # unused in subprocess mode
) -> None:
    """Entry point for the Actor subprocess. Runs the async event loop."""
    asyncio.run(_actor_async_main(config, weight_sync, prompts))


async def _actor_async_main(
    config: PipelineRLConfig,
    weight_sync: WeightSynchronizer,
    prompts: list[dict],
) -> None:
    """Async Actor main loop — true in-flight weight updates.

    Uses vLLM's AsyncLLMEngine which provides:
      - Continuous batching: multiple sequences processed concurrently
      - Non-blocking generate: each request is an async generator
      - reload_weights: updates model weights for ALL in-progress sequences

    When reload_weights is called, sequences currently being generated
    will use the new weights for their remaining tokens — this is the
    true mid-sequence in-flight update from the paper.
    """
    from vllm import SamplingParams
    from vllm.engine.arg_utils import AsyncEngineArgs
    from vllm.v1.engine.async_llm import AsyncLLM

    logger.info(f"Actor starting (CUDA_VISIBLE_DEVICES={os.environ.get('CUDA_VISIBLE_DEVICES')})")

    # -------------------------------------------------------------------------
    # Initialize AsyncLLMEngine — supports continuous batching and
    # concurrent generation with mid-sequence weight updates
    # -------------------------------------------------------------------------
    engine_args = AsyncEngineArgs(
        model=config.model_name,
        trust_remote_code=True,
        max_model_len=config.max_seq_len,
        gpu_memory_utilization=0.85,
        dtype="bfloat16",
        enforce_eager=True,
        disable_log_stats=True,
    )
    engine = AsyncLLM.from_engine_args(engine_args)

    sampling_params = SamplingParams(
        temperature=config.temperature,
        top_p=config.top_p,
        max_tokens=config.max_new_tokens,
        logprobs=1,  # per-token log probs for importance sampling
    )

    current_weight_version = 0
    total_generated = 0
    prompt_pool = list(prompts)
    done_path = os.path.join(config.weight_sync_dir, "done")
    results_dir = os.path.join(config.weight_sync_dir, "results")
    os.makedirs(results_dir, exist_ok=True)

    logger.info(
        f"Actor initialized | batch_size(H)={config.generation_batch_size} | "
        f"prompts={len(prompt_pool)} | max_tokens={config.max_new_tokens}"
    )

    # -------------------------------------------------------------------------
    # Main loop: continuously submit H requests and process completions.
    #
    # Unlike the synchronous LLM.generate(), AsyncLLMEngine lets us:
    #   1. Submit many requests concurrently
    #   2. Process completions as they arrive
    #   3. Reload weights while sequences are still generating
    #
    # This is Algorithm 2 (Actor Process) with TRUE in-flight updates:
    #   - Lines 3-8: maintain H sequences in progress
    #   - Lines 9-11: check for and apply weight updates MID-SEQUENCE
    #   - Line 12: generate next tokens (happens inside vLLM continuously)
    # -------------------------------------------------------------------------

    # Active generation tasks
    active_tasks: dict[str, asyncio.Task] = {}
    # Metadata for each request
    request_meta: dict[str, dict] = {}

    async def _submit_request(item: dict) -> str:
        """Submit a single generation request to the engine."""
        request_id = str(uuid.uuid4())
        request_meta[request_id] = {
            "item": item,
            "weight_version": current_weight_version,
        }

        async def _collect_output():
            """Collect the final output from the async generator."""
            final_output = None
            async for output in engine.generate(
                item["prompt"], sampling_params, request_id=request_id
            ):
                final_output = output
            return final_output

        task = asyncio.create_task(_collect_output())
        active_tasks[request_id] = task
        return request_id

    # Submit initial batch of H requests
    for item in random.choices(prompt_pool, k=config.generation_batch_size):
        await _submit_request(item)

    logger.info(f"Submitted initial batch of {config.generation_batch_size} requests")

    # -----------------------------------------------------------------
    # Continuous processing loop
    # -----------------------------------------------------------------
    while not os.path.exists(done_path):
        # -----------------------------------------------------------------
        # IN-FLIGHT WEIGHT UPDATE (Algorithm 2, lines 9-11)
        #
        # This is the KEY difference from conventional RL. We check for
        # new weights and reload them while sequences are ACTIVELY being
        # generated inside vLLM. After reload_weights(), all in-progress
        # sequences will generate their REMAINING tokens with the new
        # policy. This creates true mixed-policy sequences:
        #
        #   tokens 1..k   → old policy (before reload)
        #   tokens k+1..n → new policy (after reload)
        #
        # The paper shows this stays close to on-policy (Figure 7) and
        # eliminates the wasteful wait for all sequences to finish.
        # -----------------------------------------------------------------
        if weight_sync.check_for_update():
            try:
                await engine.engine_core.collective_rpc_async(
                    "reload_weights",
                    args=(None, str(weight_sync.hf_weight_dir), True),
                )
                current_weight_version = weight_sync.mark_loaded()
                logger.info(
                    f"IN-FLIGHT UPDATE: reloaded weights to version "
                    f"{current_weight_version} (with {len(active_tasks)} "
                    f"sequences still generating)"
                )
            except Exception as e:
                logger.warning(f"Weight reload failed: {e}")

        # Check for completed requests
        done_ids = []
        for req_id, task in active_tasks.items():
            if task.done():
                done_ids.append(req_id)

        # Process completed sequences and submit replacements
        for req_id in done_ids:
            task = active_tasks.pop(req_id)
            meta = request_meta.pop(req_id)

            try:
                output = task.result()
                if output is None:
                    continue

                completion = output.outputs[0]
                response_text = completion.text

                # Collect per-token log probs for importance sampling
                token_log_probs = []
                if completion.logprobs:
                    for lp in completion.logprobs:
                        if lp:
                            values = list(lp.values())
                            token_log_probs.append(
                                values[0].logprob if values else 0.0
                            )

                num_tokens = len(completion.token_ids)
                item = meta["item"]

                reward = compute_reward(
                    response=response_text,
                    ground_truth=item["answer"],
                    seq_len=num_tokens,
                    max_seq_len=config.max_seq_len,
                    length_penalty_start=config.length_penalty_start,
                    length_penalty_value=config.length_penalty_value,
                )

                # Track both start and end weight versions for token lag.
                # The start version is when the request was submitted;
                # the end version is the current version now (may have
                # changed due to in-flight updates during generation).
                # This captures the mixed-policy nature (Figure 3a).
                result = SequenceResult(
                    prompt=item["prompt"],
                    question=item["question"],
                    response=response_text,
                    ground_truth=item["answer"],
                    reward=reward,
                    log_probs=token_log_probs,
                    start_weight_version=meta["weight_version"],
                    end_weight_version=current_weight_version,
                    num_tokens=num_tokens,
                )

                # Write to filesystem for Trainer (Algorithm 2, line 5)
                _write_result(result, results_dir, total_generated)
                total_generated += 1

            except Exception as e:
                logger.warning(f"Error processing request {req_id}: {e}")

            # Refill: submit a new request to keep batch size = H
            # (Algorithm 2, lines 6-8)
            new_item = random.choice(prompt_pool)
            await _submit_request(new_item)

        if done_ids and total_generated % config.generation_batch_size == 0:
            logger.info(
                f"Actor | generated={total_generated} | "
                f"active={len(active_tasks)} | "
                f"weight_version={current_weight_version}"
            )

        # Brief yield to let the event loop process vLLM's async work
        await asyncio.sleep(0.05)

    # Cancel remaining tasks
    for task in active_tasks.values():
        task.cancel()

    logger.info(f"Actor finished | total_generated={total_generated}")


def _write_result(result: SequenceResult, results_dir: str, idx: int) -> None:
    """Write a SequenceResult to the shared results directory."""
    import pickle

    path = os.path.join(results_dir, f"result_{idx:08d}.pkl")
    tmp_path = path + ".tmp"
    with open(tmp_path, "wb") as f:
        pickle.dump(result, f)
    os.rename(tmp_path, path)
