"""Importance-weighted REINFORCE loss computation for PipelineRL.

Implements the loss function from Eq. 5 of the PipelineRL paper:

    ∇̂J_IS(π) = (1/m) Σ_j Σ_t min(c, π(y_t|x_j)/μ(y_t|x_j))
                 * (R(x_j,y_j) - baseline) * ∇ log π(y_t|x_j, y_{<t})

For verifiable tasks like GSM8K with binary rewards (1 if correct, 0
otherwise), the baseline is the mean reward in the batch (GRPO-style
group relative baseline). No learned value function is needed because
the reward is sequence-level and verifiable — we can check correctness
directly rather than estimating value.

The importance weights correct for the off-policyness created by
in-flight weight updates. In PipelineRL, a sequence may be a
"mixed-policy" sequence where early tokens were generated by an
older policy and later tokens by the current policy (Figure 3a).
"""

import logging

import torch
import torch.nn.functional as F

from .actor import SequenceResult
from .utils import compute_ess

logger = logging.getLogger("pipelinerl")


def compute_reinforce_loss(
    model: torch.nn.Module,
    tokenizer,
    batch: list[SequenceResult],
    device: torch.device,
    importance_clamp: float,
    current_step: int,
) -> tuple[torch.Tensor, dict]:
    """Compute importance-weighted REINFORCE loss for a batch.

    This implements Eq. 5 from the paper, simplified for verifiable rewards:

        loss = -(1/m) Σ_j Σ_t min(c, π_θ(y_t|x)/μ(y_t|x))
                              * (R(x,y) - baseline)
                              * log π_θ(y_t | x, y_{<t})

    Since GSM8K has binary verifiable rewards (no need for a learned
    value function), the baseline is simply the mean reward in the batch
    (GRPO-style). This is equivalent to Eq. 5 with v_φ replaced by
    the batch mean reward.

    Args:
        model: Current policy model on the trainer GPU.
        tokenizer: Tokenizer for encoding prompts + responses.
        batch: List of SequenceResult from the Actor.
        device: Training device.
        importance_clamp: Maximum importance weight (c in the paper).
        current_step: Current optimizer step for lag computation.

    Returns:
        (loss, metrics_dict) with reward, ESS, and token lag statistics.
    """
    rewards = torch.tensor([s.reward for s in batch], dtype=torch.float32)
    # GRPO-style baseline: mean reward in the batch.
    # No learned value function needed for verifiable rewards.
    baseline = rewards.mean()
    advantages = rewards - baseline

    # -------------------------------------------------------------------------
    # Token lag tracking (Figure 3a, Figure 6a)
    #
    # For each sequence, we track two lag values:
    #   - max_token_lag: lag of the FIRST token = current_step - start_version
    #     (oldest token, generated with the oldest policy)
    #   - min_token_lag: lag of the LAST token = current_step - end_version
    #     (newest token, generated after the most recent in-flight update)
    #
    # In PipelineRL (Figure 3a), earlier tokens have higher lag than later
    # tokens because in-flight updates happen mid-sequence. This is different
    # from conventional RL where all tokens in a batch have the same lag.
    # -------------------------------------------------------------------------
    max_token_lags = []  # lag of oldest token per sequence
    min_token_lags = []  # lag of newest token per sequence
    for s in batch:
        max_token_lags.append(current_step - s.start_weight_version)
        min_token_lags.append(current_step - s.end_weight_version)

    total_loss = torch.zeros(1, device=device)
    all_importance_weights = []
    valid_sequences = 0

    for i, seq in enumerate(batch):
        if not seq.response.strip() or seq.num_tokens == 0:
            continue

        # Tokenize the full sequence (prompt + response)
        full_text = seq.prompt + seq.response
        encoding = tokenizer(
            full_text,
            return_tensors="pt",
            truncation=True,
            max_length=model.config.max_position_embeddings,
        ).to(device)

        input_ids = encoding.input_ids  # (1, seq_len)

        # Find where the response starts (after the prompt tokens)
        prompt_encoding = tokenizer(
            seq.prompt, return_tensors="pt", truncation=True,
            max_length=model.config.max_position_embeddings,
        )
        prompt_len = prompt_encoding.input_ids.shape[1]
        response_len = input_ids.shape[1] - prompt_len

        if response_len <= 0:
            continue

        # Forward pass: get current policy's log probs for each token
        with torch.amp.autocast("cuda", dtype=torch.bfloat16):
            outputs = model(input_ids=input_ids)

        # Extract log probs for response tokens under CURRENT policy π_θ
        # logits[t] predicts token[t+1], so shift by prompt_len - 1
        logits = outputs.logits[0, prompt_len - 1 : -1, :]  # (response_len, vocab)
        response_ids = input_ids[0, prompt_len:]  # (response_len,)

        current_log_probs = F.log_softmax(logits.float(), dim=-1)
        current_token_log_probs = current_log_probs.gather(
            1, response_ids.unsqueeze(1)
        ).squeeze(1)  # (response_len,)

        # -----------------------------------------------------------------
        # Importance weights: w_t = π_θ(y_t|x) / μ(y_t|x)
        #
        # behavior_log_probs come from the Actor (stored per-token when
        # the sequence was generated). When lag = 0, weights ≈ 1.0.
        # When the policy has changed significantly, weights diverge,
        # and clamping to c prevents high-variance gradient estimates.
        # -----------------------------------------------------------------
        if seq.log_probs and len(seq.log_probs) > 0:
            behavior_log_probs = torch.tensor(
                seq.log_probs[:response_len], device=device, dtype=torch.float32
            )
            # Pad/truncate to match response length
            if behavior_log_probs.shape[0] < response_len:
                pad_size = response_len - behavior_log_probs.shape[0]
                behavior_log_probs = F.pad(behavior_log_probs, (0, pad_size))
            elif behavior_log_probs.shape[0] > response_len:
                behavior_log_probs = behavior_log_probs[:response_len]

            # Per-token importance ratio: exp(log π_θ - log μ)
            log_ratios = current_token_log_probs.detach() - behavior_log_probs
            importance_weights = torch.exp(log_ratios)
            # Clamp to c to reduce variance (paper: c = 5)
            importance_weights = torch.clamp(importance_weights, max=importance_clamp)
        else:
            # No behavior log probs → treat as on-policy (weight = 1)
            importance_weights = torch.ones(response_len, device=device)

        all_importance_weights.append(importance_weights)

        # -----------------------------------------------------------------
        # Weighted REINFORCE loss for this sequence (Eq. 5):
        #   loss_j = -Σ_t w_t * (R - baseline) * log π_θ(y_t | x, y_{<t})
        #
        # Note: Eq. 5 sums over tokens WITHOUT dividing by T_j. The only
        # normalization is 1/m (dividing by number of sequences). This
        # matches the paper exactly.
        # -----------------------------------------------------------------
        advantage = advantages[i].to(device)
        seq_loss = -(importance_weights * advantage * current_token_log_probs).sum()
        total_loss = total_loss + seq_loss
        valid_sequences += 1

    if valid_sequences > 0:
        total_loss = total_loss / valid_sequences

    # Compute Effective Sample Size from all importance weights (Eq. 6)
    # ESS near 1.0 = on-policy, ESS near 0 = highly off-policy
    if all_importance_weights:
        flat_weights = torch.cat(all_importance_weights)
        ess = compute_ess(flat_weights)
    else:
        ess = 1.0

    # Sequence length and token count stats
    token_counts = [s.num_tokens for s in batch]
    batch_total_tokens = sum(token_counts)
    avg_seq_length = batch_total_tokens / len(batch) if batch else 0.0

    batch_metrics = {
        "mean_reward": rewards.mean().item(),
        "ess": ess,
        # Token lag stats (Figure 3a, 6a)
        "max_token_lag": max(max_token_lags) if max_token_lags else 0,
        "min_token_lag": min(min_token_lags) if min_token_lags else 0,
        "avg_token_lag": sum(max_token_lags) / len(max_token_lags) if max_token_lags else 0.0,
        "mixed_policy_seqs": sum(
            1 for s in batch if s.start_weight_version != s.end_weight_version
        ),
        # Throughput stats
        "batch_total_tokens": batch_total_tokens,
        "avg_seq_length": avg_seq_length,
    }

    return total_loss, batch_metrics
